@startuml
scale 2


node "<<Device>>\n Light Square" as light_box {
    node "<<Device>>\nFadecandy LED Driver" as fadecandy
    node "<<Device>>\nLED Pixel" as led
    led "512" <-- "1" fadecandy : "PWM signal"
}


node "<<Device>>\n Computer" as pc {
    node "<<OS>>\nMacOS" as macOS {
        node "<<Application>>\nFadecandy REST" as rest 
        node "<<Application>>\nFadecandy Frontend" as frontend 
        node "<<Application>>\nFadecandy OPC Server" as opc
        node "<<Application>>\nOpenFrameworks\nEffects App" as of
        fadecandy "1..19" -- "1..*" opc : USB
        rest "1" .> "1" opc : <<deploy>>
        of "1" --> "1..*" opc : TCP
        rest "1" -- "1" frontend
    }
}

@enduml