@startuml
scale 2


node "<<Device>>\nŠviesos efektų įrenginys" as light_box {
    node "<<Device>>\nFadecandy LED Driver" as fadecandy
    node "<<Device>>\nLED strips" as led
    led <-- fadecandy : "PWM signalas"
}


node "<<Device>>\nKompiuteris" as pc {
    node "<<OS>>\nMacOS" as macOS {
        node "<<Application>>\nĮrenginių REST" as rest 
        node "<<Application>>\nFadecandy OPC Server" as opc
        node "<<Application>>\nEffects Mixer" as of

        fadecandy -- opc : USB
        rest .> opc : <<deploy>>
        of -- rest : HTTP
        of --> opc : WebSockets
    }
}


@enduml