@startuml SystemWindow
scale 2
autonumber "<b>[0]"

actor Human

participant SystemWindow

participant AppContext
participant BoxClient
participant AudioClient
participant LedClient


[-> SystemWindow : setup()
activate SystemWindow

SystemWindow -> AppContext : audio.setup()
activate AppContext
AppContext -> AudioClient : setup()
activate AudioClient
AppContext <-- AudioClient
SystemWindow <-- AppContext

SystemWindow -> AppContext : box.setup()
AppContext -> BoxClient : setup()
activate BoxClient
AppContext <-- BoxClient
SystemWindow <-- AppContext 

[<-- SystemWindow
deactivate SystemWindow

[-> SystemWindow : update()
    
activate SystemWindow

SystemWindow -> AppContext : audio.update()
AppContext -> AudioClient : update()
AppContext <-- AudioClient
SystemWindow <-- AppContext

SystemWindow -> AppContext : box.update()
AppContext -> BoxClient : update()
AppContext <-- BoxClient
SystemWindow <-- AppContext

[<-- SystemWindow
deactivate SystemWindow

[-> SystemWindow : draw()
activate SystemWindow

SystemWindow -> AppContext : audio.draw()
AppContext -> AudioClient : draw()
AppContext <-- AudioClient
SystemWindow <-- AppContext

SystemWindow -> AppContext : box.draw()
AppContext -> BoxClient : draw()

AppContext <-- BoxClient
SystemWindow <-- AppContext

[<-- SystemWindow
deactivate SystemWindow

[-> SystemWindow : exit()
activate SystemWindow
SystemWindow -> AppContext : audio.exit()
AppContext -> AudioClient : exit()
AppContext <-- AudioClient
deactivate AudioClient
SystemWindow <-- AppContext

SystemWindow -> AppContext : box.exit()
AppContext -> BoxClient : exit()
AppContext <-- BoxClient
deactivate BoxClient
SystemWindow <-- AppContext
deactivate AppContext
[<-- SystemWindow
deactivate SystemWindow

Human -> SystemWindow : Start Fadecandy Process
activate SystemWindow
SystemWindow -> BoxClient : start()
SystemWindow <-- BoxClient
Human <-- SystemWindow
deactivate SystemWindow

Human -> SystemWindow : Stop Fadecandy Process
activate SystemWindow
SystemWindow -> BoxClient : stop()
SystemWindow <-- BoxClient
Human <-- SystemWindow
deactivate SystemWindow

Human -> SystemWindow : Restart Fadecandy Process
activate SystemWindow
SystemWindow -> BoxClient : restart()
SystemWindow <-- BoxClient
Human <-- SystemWindow
deactivate SystemWindow

Human -> SystemWindow : Restart Connection to Fadecandy
activate SystemWindow
SystemWindow -> BoxClient : led.restart()
BoxClient -> LedClient : restart()
BoxClient <-- LedClient
SystemWindow <-- BoxClient
Human <-- SystemWindow
deactivate SystemWindow

Human -> SystemWindow : Set Fadecandy Address
activate SystemWindow
SystemWindow -> BoxClient : led.setAddress()
BoxClient -> LedClient : setAddress()
BoxClient <-- LedClient
SystemWindow <-- BoxClient
Human <-- SystemWindow
deactivate SystemWindow


@enduml