@startuml
scale 2
autonumber "<b>[0]"

participant AudioClient
participant ofxAudioAnalyzer


[-> AudioClient: exit()
activate AudioClient
AudioClient -> ofxAudioAnalyzer : exit()
activate ofxAudioAnalyzer
AudioClient <-- ofxAudioAnalyzer
deactivate ofxAudioAnalyzer
[<-- AudioClient
deactivate AudioClient


[-> AudioClient: update()
activate AudioClient
AudioClient -> ofxAudioAnalyzer : analyze(ofSoundBuffer)
activate ofxAudioAnalyzer
AudioClient <-- ofxAudioAnalyzer
deactivate ofxAudioAnalyzer
AudioClient -> ofxAudioAnalyzer : Get Analysis Results
activate ofxAudioAnalyzer
AudioClient <-- ofxAudioAnalyzer
deactivate ofxAudioAnalyzer
[<-- AudioClient 
deactivate AudioClient

@enduml