@startuml Fadecandy REST Fc Service
scale 2
autonumber "<b>[0]"

participant FadecandyService
participant FadecandyController
participant FadecandyDriver
participant FadecandyProcessReader

[-> FadecandyService : get<FadecandyLocation.Start>
activate FadecandyService
FadecandyService -> FadecandyController : start()
activate FadecandyController
FadecandyController -> FadecandyDriver : start()
activate FadecandyDriver
FadecandyDriver -> FadecandyDriver : Write Latest Config to Disk
FadecandyDriver -> FadecandyDriver : Start Fadecandy Server Process
FadecandyDriver -> FadecandyProcessReader : Start Process Logs Reader
activate FadecandyProcessReader
FadecandyDriver <-- FadecandyProcessReader
deactivate FadecandyProcessReader
FadecandyController <-- FadecandyDriver
deactivate FadecandyDriver
FadecandyService <-- FadecandyController
deactivate FadecandyController
[<-- FadecandyService : Execution Response Model
deactivate FadecandyService

[-> FadecandyService : get<FadecandyLocation.Stop>
activate FadecandyService
FadecandyService -> FadecandyController : stop()
activate FadecandyController
FadecandyController -> FadecandyDriver : kill()
activate FadecandyDriver
FadecandyDriver -> FadecandyDriver : Kill Fadecandy Process
FadecandyDriver -> FadecandyProcessReader : Kill Process Logs Reader
activate FadecandyProcessReader
FadecandyDriver <-- FadecandyProcessReader
deactivate FadecandyProcessReader
FadecandyController <-- FadecandyDriver
deactivate FadecandyDriver
FadecandyService <-- FadecandyController
deactivate FadecandyController
[<-- FadecandyService : Execution Response Model
deactivate FadecandyService

[-> FadecandyService : get<FadecandyLocation>
activate FadecandyService
FadecandyService -> FadecandyController : getStatus()
activate FadecandyController
FadecandyService <-- FadecandyController : status
deactivate FadecandyController
[<-- FadecandyService : Execution Response Model
deactivate FadecandyService

[-> FadecandyService : get<FadecandyLocation.Restart>
activate FadecandyService
FadecandyService -> FadecandyController : restart()
activate FadecandyController
FadecandyController -> FadecandyDriver : kill()
activate FadecandyDriver
FadecandyController <-- FadecandyDriver
FadecandyController -> FadecandyDriver : start()
FadecandyController <-- FadecandyDriver
deactivate FadecandyDriver
FadecandyService <-- FadecandyController
deactivate FadecandyController
[<-- FadecandyService : Execution Response Model
deactivate FadecandyService

[-> FadecandyService : get<FadecandyLocation.Config>
activate FadecandyService
FadecandyService -> FadecandyController : getConfig()
activate FadecandyController
FadecandyController -> FadecandyDriver : getConfig()
activate FadecandyDriver
FadecandyController <-- FadecandyDriver : config
deactivate FadecandyDriver
FadecandyService <-- FadecandyController : config
deactivate FadecandyController
[<-- FadecandyService : Execution Response Model
deactivate FadecandyService

[-> FadecandyService : post<FadecandyLocation.Config>
activate FadecandyService
FadecandyService -> FadecandyController : setConfig(FcConfig)
activate FadecandyController
FadecandyController -> FadecandyDriver : setConfig(FcConfig)
activate FadecandyDriver
FadecandyController <-- FadecandyDriver
FadecandyController -> FadecandyDriver : kill()
FadecandyController <-- FadecandyDriver
FadecandyController -> FadecandyDriver : start()
FadecandyController <-- FadecandyDriver
deactivate FadecandyDriver
FadecandyService <-- FadecandyController
deactivate FadecandyController
[<-- FadecandyService : Execution Response Model
deactivate FadecandyService


@enduml