@startuml VisualMixerWindow
scale 2
autonumber "<b>[0]"

participant VisualMixerWindow

participant AppContext
participant LedClient


[-> VisualMixerWindow : exit()
activate VisualMixerWindow
VisualMixerWindow -> AppContext : led.exit()
activate AppContext
AppContext -> LedClient : exit()
activate LedClient

AppContext <-- LedClient
deactivate LedClient
VisualMixerWindow <-- AppContext
deactivate AppContext
[<-- VisualMixerWindow

@enduml