@startuml Panaudojimo Atvėjai
scale 2
left to right direction


actor :Naudotojas: as client

(Keisti technės įrangos konfiguraciją) as (tech_view_config)
(Peržiurėti techinės įrangos būseną) as (tech_view_state)
(Perkrauti techinės įrangos valdiklio procesą) as (tech_reboot)
(Stabdyti techinės įrangos valdiklio procesą) as (tech_stop)
(Paleisti techinę įrangos valdiklio procesą) as (tech_start)


client -- tech_view_config
client -- tech_view_state
client -- tech_reboot
client -- tech_stop
client -- tech_start

@enduml